# PowerShell script to start the scheduler daemon at Windows startup
# This script handles environment validation, process detection, and automatic restart

# PF - NOTE that this script was generated by copilot.  It tried very hard to not have the terminal
# window pop up, but it didn't succeed.  I'm leaving this as a TODO to fix later.

param(
    [switch]$NoRestart = $false
)

# Change to the project directory
$ProjectDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $ProjectDir

# Set up logging
$LogDir = Join-Path $ProjectDir "logs"
if (-not (Test-Path $LogDir)) {
    New-Item -ItemType Directory -Path $LogDir -Force | Out-Null
}
$StartupLog = Join-Path $LogDir "scheduler_startup.log"

function Write-StartupLog {
    param([string]$Message)
    $Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $LogMessage = "[$Timestamp] $Message"
    Write-Host $LogMessage
    Add-Content -Path $StartupLog -Value $LogMessage
}

Write-StartupLog "========== Scheduler Startup Script =========="
Write-StartupLog "Project Directory: $ProjectDir"

# Validate environment
if (-not (Test-Path ".env")) {
    Write-StartupLog "ERROR: .env file not found. Please create .env with required settings."
    exit 1
}

# Load RUNTIME_ROOT from .env file
$RuntimeRoot = $null
Get-Content ".env" | ForEach-Object {
    if ($_ -match '^RUNTIME_ROOT=(.+)$') {
        $RuntimeRoot = $matches[1].Trim()
    }
}

if (-not $RuntimeRoot) {
    Write-StartupLog "ERROR: RUNTIME_ROOT not found in .env file"
    exit 1
}

Write-StartupLog "Runtime Root: $RuntimeRoot"

# Check for existing scheduler process
$PidFile = Join-Path $RuntimeRoot "scheduler.pid"
if (Test-Path $PidFile) {
    Write-StartupLog "WARNING: PID file exists at $PidFile"
    Write-StartupLog "Checking if scheduler is already running..."
    
    # Get scheduler processes
    $SchedulerProcesses = Get-Process -Name "python" -ErrorAction SilentlyContinue | 
        Where-Object { $_.CommandLine -like "*main.py*schedule*" }
    
    if ($SchedulerProcesses) {
        Write-StartupLog "ERROR: Scheduler is already running (PID: $($SchedulerProcesses.Id -join ', '))"
        Write-StartupLog "If this is incorrect, delete the PID file and try again: $PidFile"
        exit 1
    } else {
        Write-StartupLog "No running scheduler found, removing stale PID file"
        Remove-Item $PidFile -Force
    }
}

# Main scheduler loop with restart capability
$MaxRestarts = 5
$RestartCount = 0
$RestartDelay = 10  # seconds

while ($true) {
    Write-StartupLog "Starting scheduler (attempt $($RestartCount + 1))"
    
    try {
        # Run the scheduler using uv (completely hidden using .NET ProcessStartInfo)
        $ProcessStartInfo = New-Object System.Diagnostics.ProcessStartInfo
        $ProcessStartInfo.FileName = "uv"
        $ProcessStartInfo.Arguments = "run python main.py schedule"
        $ProcessStartInfo.UseShellExecute = $false
        $ProcessStartInfo.CreateNoWindow = $true
        $ProcessStartInfo.RedirectStandardOutput = $false
        $ProcessStartInfo.RedirectStandardError = $false
        $ProcessStartInfo.WorkingDirectory = $ProjectDir
        
        $Process = New-Object System.Diagnostics.Process
        $Process.StartInfo = $ProcessStartInfo
        $Process.Start() | Out-Null
        $Process.WaitForExit()
        
        $ExitCode = $Process.ExitCode
        Write-StartupLog "Scheduler exited with code: $ExitCode"
        
        # If exit code is 0, it was a clean shutdown - don't restart
        if ($ExitCode -eq 0) {
            Write-StartupLog "Clean shutdown detected, exiting"
            break
        }
        
        # If NoRestart flag is set, exit after first run
        if ($NoRestart) {
            Write-StartupLog "NoRestart flag set, exiting"
            exit $ExitCode
        }
        
        # Check if we've exceeded max restarts
        $RestartCount++
        if ($RestartCount -ge $MaxRestarts) {
            Write-StartupLog "ERROR: Maximum restart attempts ($MaxRestarts) reached"
            exit 1
        }
        
        # Wait before restarting
        Write-StartupLog "Waiting $RestartDelay seconds before restart..."
        Start-Sleep -Seconds $RestartDelay
        
    } catch {
        Write-StartupLog "ERROR: Failed to start scheduler: $_"
        
        if ($NoRestart) {
            exit 1
        }
        
        $RestartCount++
        if ($RestartCount -ge $MaxRestarts) {
            Write-StartupLog "ERROR: Maximum restart attempts ($MaxRestarts) reached"
            exit 1
        }
        
        Write-StartupLog "Waiting $RestartDelay seconds before restart..."
        Start-Sleep -Seconds $RestartDelay
    }
}

Write-StartupLog "Scheduler startup script finished"
